import json
import sys

def generate(input_json):
    try:
        data = json.loads(input_json)
        
        if not isinstance(data, dict):
            return "Error: Input must be a JSON object"
        
        result = "// Generated by Simple Plugin\n"
        result += "// Simple key-value pairs:\n\n"
        
        for key, value in data.items():
            result += f"// {key}: {value}\n"
        
        return result
        
    except json.JSONDecodeError as e:
        return f"Error: Invalid JSON - {e}"
    except Exception as e:
        return f"Error: {e}"

if __name__ == "__main__":
    input_data = sys.stdin.read().strip()
    result = generate(input_data)
    print(result)
