name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    - name: Download dependencies
      run: go mod download
    - name: Run tests
      run: go test ./... -v
    - name: Build
      run: |
        go build -o bin/devtoolbox ./cmd/cli
        go build -o bin/devtoolbox-web ./cmd/web

  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci
    - name: Run tests
      working-directory: ./frontend
      run: npm test -- --run
    - name: Build
      working-directory: ./frontend
      run: npm run build

  python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: python -m pytest tests/python/ -v
    - name: Test plugins
      run: |
        echo '{"name": "string", "age": "number"}' | python plugins/official/ts_interface_gen.py

  integration:
    runs-on: ubuntu-latest
    needs: [go, frontend, python]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        go mod download
        cd frontend && npm ci
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run integration tests
      run: |
        go test ./tests/go/... -v
        cd frontend && npm test -- --run
        python -m pytest tests/python/ -v
